trigger:
  branches:
    include:
      - master

variables:
  - group: dcaprio

pool:
  vmImage: $(VM_IMAGE_NAME)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build NestJS app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: 'drop'
    displayName: 'Publish artifact'

  - task: AzureRmWebAppDeployment@4
    inputs:
      azureSubscription: $(AzureSubscription)
      WebAppName: $(BackendAppName)
      Package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Deploy to Azure Web App'
