steps:
  - script: |
      npm install
      npm run build
    displayName: 'Build NestJS App'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

  - task: AzureRmWebAppDeployment@4
    inputs:
      azureSubscription: 'DCaprio-DIA-Sandbox'
      appType: 'webApp'
      WebAppName: 'dcpario-backend'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
